# Generated by Django 3.1.4 on 2023-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
