# Generated by Django 3.1.4 on 2023-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
