# Generated by Django 3.1.4 on 2023-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20230701_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
